apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    args:
    - /bin/bash
    - -c 
    - sleep 10; exit 1
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
status: {}
